#' ---
#' title: "Predictors for BAM Generalized National Models"
#' author: "Peter Solymos <solymos@ualberta.ca>"
#' date: "`r as.Date(Sys.time())`"
#' output: pdf_document
#' ---
#+ echo=FALSE
knitr::opts_chunk$set(eval=FALSE)
ROOT <- "E:/MelinaStuff/BAM/NationalModelv4.1/runNationalModel"
#par(las=1, scipen=999)
#'
#' Making bundle with predictors and buffered BCR indicators
#'
#' # Preamble
library(mefa)
library(mefa4)
library(intrval)
library(sf)
library(sp)
library(raster)

LAEA <- "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
lcc_crs <- "+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"

#' Load data and set up coordinates
load(file.path(ROOT, "data/outsample", "PKEYannualcombo_bcr.RData"))
sf <- sf::st_as_sf(dd, coords = c("longitude","latitude"))
sf <- st_set_crs(sf, LAEA)
sf <- st_transform(sf, lcc_crs)

##############
  # Check Map coordinate
  plot(st_geometry(sf))
##############
###################################
##      Create dd with cyid
###################################

#' Create an empty matrix
xy <- st_coordinates(sf)
bb <- bbox(xy)
r <- raster(
  xmn=bb["x", "min"],
  xmx=bb["x", "max"],
  ymn=bb["y", "min"],
  ymx=bb["y", "max"],
  res=250,
  crs=st_crs(sf)$proj4string)

#' spatial grid IDs
r10 <- aggregate(r, fact=10)
values(r10) <- seq_len(ncell(r10))
dd$cid <- extract(r10, xy)
#' cluster + year IDs
dd$cyid <- interaction(dd$cid, dd$YEAR, sep="_", drop=TRUE)


###################################
##      Create OFF
###################################
##Create off variables using R.data  generated by the offset (BAM, WT, BBS)
load("E:/MelinaStuff/BAM/NationalModelv4.1/offset/National Models/0_data/processed_1/BAM-data-processed-2021-12-03.RData", bamenv <- new.env())
#ls(bamenv)
#head(bamenv$OFF)
OFFbam <- bamenv$OFF
load("E:/MelinaStuff/BAM/NationalModelv4.1/offset/National Models/0_data/processed_1/WT-data-processed-2021-12-03.RData", wtenv <- new.env())
#ls(bamenv)
#head(wtenv$OFF)
OFFwt <- wtenv$OFF
load("E:/MelinaStuff/BAM/NationalModelv4.1/offset/National Models/0_data/processed_1/BBS-data-processed-2021-12-04.RData", bbsenv <- new.env())
#ls(bamenv)
#head(bbsenv$OFF)
OFFbbs <- bbsenv$OFF

#Check structure
nrow(OFFbam) # 244812
ncol(OFFbam) # 151
nrow(OFFwt)  # 78401
ncol(OFFwt)  # 143
nrow(OFFbbs) # 813522
ncol(OFFbbs) # 151

#subset specific offset based on pkey
OFFbam1 <- subset(OFFbam, rownames(OFFbam) %in% dd$PKEY)
#nrow(testbam) #113679 vs  244812

OFFwt1 <- subset(OFFwt, rownames(OFFwt) %in% dd$PKEY)
#nrow(testwt) # 59175 vs 78401

OFFbbs1 <- subset(OFFbbs, rownames(OFFbbs) %in% dd$PKEY)
#nrow(testbbs) # 775128 vs 813522

#length(unique(dd$PKEY)) #1141301


# Turn matrix to df and bind 
OFFbam1.df <- as.data.frame(OFFbam1)
OFFwt1.df <- as.data.frame(OFFwt1)
OFFbbs1.df <- as.data.frame(OFFbbs1)
OFF <- dplyr::bind_rows(OFFbam1.df, OFFwt1.df,  OFFbbs1.df)
OFF_mtx <-data.matrix(OFF, rownames.force = rownames(OFF))

off <- OFF_mtx

###################################
##      CReate yy
###################################
pkeylist <-dd$PKEY
specieslist <- colnames(OFFbam)

ybam <- bamenv$y
ywt <- wtenv$y
ybbs <- bbsenv$y

#subset specific offset based on pkey
ybam1 <- ybam[rownames(ybam)%in% pkeylist, colnames(ybam) %in% specieslist]
ywt_1 <- ywt[rownames(ywt)%in% pkeylist, colnames(ywt) %in% specieslist]
ybbs1 <- ybbs[rownames(ybbs)%in% pkeylist, colnames(ybbs) %in% specieslist]

  # finding what's missing in WT
  miswt = colnames(ybam1)[!colnames(ybam1) %in% colnames(ywt_1)]
  #"BGGN" "EATO" "FISP" "NOPA" "RHWO" "ROSA" "YBCU" "YTVI"
  miswtl = as.vector(numeric(length(miswt)), "list")
  names(miswtl) = miswt
  ywt1 = do.call(cbind, c(ywt_1, miswtl))

yy <- rbind(ybam1, ywt1, ybbs1)


#' Save
save(dd, yy, off, file=file.path(ROOT, "data/outsample", "NatMod41-2021-12-10.RData"))
